### ISSUE TITLE
libtorch with args "c++" did not execute successfully

### ISSUE THREAD

**Issue by ASB1993** [tensordot/syntaxdot#200]
Hey guys, 

I am trying to build SyntaxDot on Windows Computer. I already set up WSL, and followed the instructions on the installation page. I added the environment variable and Path for rustup manually. Nevertheless, when running "nix-env \
  -f https://github.com/tensordot/syntaxdot/archive/main.tar.gz \
  -iA packages.x86_64-linux.syntaxdot"
 
it compiles everything, and in the end it throws the following error:
  
    error occurred: Command "/nix/store/35pnk5kwi26m3ph2bc7dxwjnavpzl8cn-gcc-wrapper-10.3.0/bin/c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/nix/store/0ripbpgjagf2yfqgzy0p11xx2ph7sjnl-torch-join/include" "-I" "/nix/store/0ripbpgjagf2yfqgzy0p11xx2ph7sjnl-torch-join/include/torch/csrc/api/include" "-Wl,-rpath=/nix/store/0ripbpgjagf2yfqgzy0p11xx2ph7sjnl-torch-join/lib" "-std=c++14" "-D_GLIBCXX_USE_CXX11_ABI=1" "-o" "/tmp/nix-build-syntaxdot-0.4.0.drv-0/syntaxdot/target/x86_64-unknown-linux-gnu/release/build/torch-sys-f8c64a951705a779/out/libtch/torch_api.o" "-c" "libtch/torch_api.cpp" with args "c++" did not execute successfully (status code exit code: 1).

What could I possibly do to change it? 

Thanks in advance!

**Comment by danieldk** [comment]
The Nix flake is outdated. I'll look into it as soon as possible.

**Comment by danieldk** [comment]
Sorry for the delay, I was AFK on holiday, should be fixed in 1c1f222c42fcd4861d4cb9b71f1a6786f1548fc5.
