### ISSUE TITLE
Internal torch error: Could not run 'aten::empty.memory_format' with arguments from the 'CUDA' backend

### ISSUE THREAD

**Issue by ASB1993** [tensordot/syntaxdot#203]
Hi, 
I am trying to train the model. I have tried libtorch1.9.0 for CUDA 10.2 and 11.1, neither of them seem to work. 

Error: Cannot construct model

Caused by:
    Internal torch error: Could not run 'aten::empty.memory_format' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty.memory_format' is only available for these backends: [CPU, Meta, MkldnnCPU, SparseCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
    
    CPU: registered at aten/src/ATen/RegisterCPU.cpp:16286 [kernel]
    Meta: registered at aten/src/ATen/RegisterMeta.cpp:9460 [kernel]
    MkldnnCPU: registered at aten/src/ATen/RegisterMkldnnCPU.cpp:563 [kernel]
    SparseCPU: registered at aten/src/ATen/RegisterSparseCPU.cpp:959 [kernel]
    BackendSelect: registered at aten/src/ATen/RegisterBackendSelect.cpp:609 [kernel]
    Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
    ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:60 [backend fallback]
    AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    UNKNOWN_TENSOR_TYPE_ID: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    AutogradMLC: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_4.cpp:9226 [autograd kernel]
    Tracer: registered at ../torch/csrc/autograd/generated/TraceType_4.cpp:9909 [kernel]
    Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:255 [backend fallback]
    Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1019 [backend fallback]
    VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
    
    Exception raised from reportError at ../aten/src/ATen/core/dispatch/OperatorEntry.cpp:399 (most recent call first):
    frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f430d9401d9 in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libc10.so)
    frame #1: <unknown function> + 0xf15b20 (0x7f430eaa2b20 in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libtorch_cpu.so)
    frame #2: c10::impl::OperatorEntry::reportError(c10::DispatchKey) const + 0x863 (0x7f430eb1f393 in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libtorch_cpu.so)
    frame #3: <unknown function> + 0x1adef73 (0x7f430f66bf73 in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libtorch_cpu.so)
    frame #4: at::empty(c10::ArrayRef<long>, c10::TensorOptions, c10::optional<c10::MemoryFormat>) + 0x293 (0x7f430f241a13 in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libtorch_cpu.so)
    frame #5: at::native::randn(c10::ArrayRef<long>, c10::optional<at::Generator>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 0x52d (0x7f430eecd39d in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libtorch_cpu.so)
    frame #6: at::native::randn(c10::ArrayRef<long>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>) + 0x51 (0x7f430eecd4f1 in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libtorch_cpu.so)
    frame #7: <unknown function> + 0x1cc0706 (0x7f430f84d706 in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libtorch_cpu.so)
    frame #8: <unknown function> + 0x1ad94cd (0x7f430f6664cd in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libtorch_cpu.so)
    frame #9: <unknown function> + 0x1ae2b5b (0x7f430f66fb5b in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libtorch_cpu.so)
    frame #10: at::randn(c10::ArrayRef<long>, c10::TensorOptions) + 0x298 (0x7f430f2a3b48 in /content/drive/MyDrive/SyntaxDot/libtorch/lib/libtorch_cpu.so)
    frame #11: <unknown function> + 0x2de84b (0x55f11554784b in /root/.cargo/bin/syntaxdot)
    frame #12: <unknown function> + 0x2c6553 (0x55f11552f553 in /root/.cargo/bin/syntaxdot)
    frame #13: <unknown function> + 0x2ca34e (0x55f11553334e in /root/.cargo/bin/syntaxdot)
    frame #14: <unknown function> + 0x2cbb6b (0x55f115534b6b in /root/.cargo/bin/syntaxdot)
    frame #15: <unknown function> + 0x2c1bca (0x55f11552abca in /root/.cargo/bin/syntaxdot)
    frame #16: <unknown function> + 0xe8785 (0x55f115351785 in /root/.cargo/bin/syntaxdot)
    frame #17: <unknown function> + 0x1728e0 (0x55f1153db8e0 in /root/.cargo/bin/syntaxdot)
    frame #18: <unknown function> + 0x17b961 (0x55f1153e4961 in /root/.cargo/bin/syntaxdot)
    frame #19: <unknown function> + 0x15e05c (0x55f1153c705c in /root/.cargo/bin/syntaxdot)
    frame #20: <unknown function> + 0xd6781 (0x55f11533f781 in /root/.cargo/bin/syntaxdot)
    frame #21: <unknown function> + 0xc60db (0x55f11532f0db in /root/.cargo/bin/syntaxdot)
    frame #22: <unknown function> + 0xe8f73 (0x55f115351f73 in /root/.cargo/bin/syntaxdot)
    frame #23: <unknown function> + 0xe8f8d (0x55f115351f8d in /root/.cargo/bin/syntaxdot)
    frame #24: <unknown function> + 0x3e39ea (0x55f11564c9ea in /root/.cargo/bin/syntaxdot)
    frame #25: <unknown function> + 0xc6952 (0x55f11532f952 in /root/.cargo/bin/syntaxdot)
    frame #26: __libc_start_main + 0xe7 (0x7f430c714bf7 in /lib/x86_64-linux-gnu/libc.so.6)
    frame #27: <unknown function> + 0x7e7fa (0x55f1152e77fa in /root/.cargo/bin/syntaxdot)

**Comment by danieldk** [comment]
Could you perhaps show add the command you are using to start finetuning. Additionally, what is the output for

```
echo $LD_LIBRARY_PATH
```

and

```
ls -l /content/drive/MyDrive/SyntaxDot/libtorch/lib/
```

I think this error could happen when you have built SyntaxDot against the CUDA version and are running against the CPU version or vise versa. The best thing to do during the build is to set `LIBTORCH` to your downloaded libtorch directory. So I think in your case:

```
export LIBTORCH=/content/drive/MyDrive/SyntaxDot/libtorch
cd syntaxdot
cargo build --release
```

By default, the `tch` Rust library downloads a non-GPU version of libtorch. You then run into the issue that the compiled binary is not properly linked against the libtorch CUDA libraries.

(I am sorry that linking against libtorch CUDA is such a mess.)

**Comment by ASB1993** [comment]
Hey, thanks for the answer.
So, !/root/.cargo/bin/syntaxdot prepare /content/drive/MyDrive/SyntaxDot/syntaxdot.conf /content/drive/MyDrive/SyntaxDot/tuebadz-conllu-new.conllu works.

I might have to add that I am trying to run the finetuning process on Google Colab, where I was able to install an instance of rustup to cargo install syntaxdot. The problem is, that I cannot really create a rustup environment in which I could use Python, therefore, I had to improvise. However, without GPU, I cannot train the model therefore, I am trying to use Google Colab.

![grafik](https://user-images.githubusercontent.com/44137052/133934608-6c76a9e7-5e6a-4f34-a82e-0e4c1f3d9a91.png)
![grafik](https://user-images.githubusercontent.com/44137052/133934628-6eefe60f-69a3-41a5-ab1b-34050498d513.png)
![grafik](https://user-images.githubusercontent.com/44137052/133934669-7fa94e43-0283-414f-8fa4-4e38d9646346.png)

Thanks!

**Comment by ASB1993** [comment]
No solution yet?

**Comment by danieldk** [comment]
Did you set the `LIBTORCH` environment variablebefore building SyntaxDot, to ensure that it's built against the GPU version? You'd need to set it to the main director, I think in your case it would be:

```
export LIBTORCH=/content/drive/MyDrive/SyntaxDot/libtorch
```

**Comment by ASB1993** [comment]
yes, I have to use os.environ, but yes, putting it before build worked... however, I now get the following error after starting training:

```
thread 'main' panicked at 'Head out of bounds', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/udgraph-0.7.0/src/graph.rs:452:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by danieldk** [comment]
Interesting. That is a bug, however, that should only happen if the input data has incorrect dependencies (heads that do not exist). If the input does not have dependencies at all, remove the biaffine layer from the syntaxdot configuration.

**Comment by ASB1993** [comment]
Actually, I already removed the biaffine layer from the configuration. Nevertheless, the error occurs. I am using the tuebadz conllu data, and changed the misc column so that only the named entity tags are available (e.g. NE=B-PER). So, what else could I do to solve the issue?

**Comment by danieldk** [comment]
The bug is that this should be an error, not an assertion. The error means that the input data is invalid. The CoNLL-U data is read as graphs. If you get this error, it means one token has a CoNLL-U head field that has an incorrect head. E.g. if you have a token like

```
32      ze      ze      PRON    PRON-pers       Person=3|PronType=Prs   35      nsubj   _        _
```

Which indicates that 35 is its head, but there is no 35th token.

**Comment by ASB1993** [comment]
Thanks for the answer. Also, I noticed, that \d+-\d+ for words like "im" (in dem), "ins" (in das), "übers" (über das) are not allowed, even though it is a valid coNLL-U formatting.
